---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: integration-deployment-pipeline-test
  name: integration-deployment-pipeline-test
spec:
  triggers:
    - type: "GitHub"
      github:
        secret: "secret"
  source:
    git:
      uri: "https://github.com/fngnv/pipeline-test"
      ref: "master"
  strategy:
    dockerStrategy: {}
  output:
    to:
      kind: ImageStreamTag
      name: integration-deployment-pipeline-test:latest
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: integration-deployment-pipeline-test
  name: integration-deployment-pipeline-test
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: integration-deployment-pipeline-test
  labels:
    app: integration-deployment-pipeline-test
spec:
  replicas: 1
  strategy:
    type: Rolling
  selector:
    app: integration-deployment-pipeline-test
  template:
    metadata:
      labels:
        app: integration-deployment-pipeline-test
    spec:
      containers:
        - name: integration-deployment-pipeline-test
          image: image-registry.openshift-image-registry.svc:5000/testproject/integration-deployment-pipeline-test:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - integration-deployment-pipeline-test
        from:
          kind: ImageStreamTag
          name: integration-deployment-pipeline-test:latest
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: integration-deployment-pipeline-test
  name: integration-deployment-pipeline-test
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: integration-deployment-pipeline-test
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    router.openshift.io/override-host: "true"
  labels:
    app: integration-deployment-pipeline-test
    application: integration-deployment-pipeline-test
  name: integration-deployment-pipeline-test
spec:
  to:
    kind: Service
    name: integration-deployment-pipeline-test
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  port:
    targetPort: 8080